# main text of home
name: Saurabh Ranjan
bio: Metacognition, Reality Monitoring, Cognitive Neuroscience, AI, Consciousness

# twitter summary info
description: Personal Website

picture: assets/images/greyscale.jpg

url: https://saurabhr.github.io
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
blue sky: saurabhr.bsky.social
twitter/X: saurabhbluebird
github: saurabhr
email: saurabh.ranjan@ufl.edu

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
