# main text of home
name: Saurabh Ranjan
bio: Metacognition, Reality Monitoring, Cognitive Neuroscience, AI, Consciousness

# twitter summary info
description: Personal Website

picture: assets/images/greyscale.jpg

url: https://saurabhr.github.io
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
facebook: myfacebook
twitter: mytwitter
github: https://github.com/saurabhr
email: ranjan.saurabh@outlook.com

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
